"""Initial migration

Revision ID: 158bdafd216e
Revises: 
Create Date: 2025-05-26 11:17:30.855614

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "158bdafd216e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("issuedbooks_user_id_fkey", "issuedbooks", type_="foreignkey")
    op.drop_constraint("issuedbooks_book_id_fkey", "issuedbooks", type_="foreignkey")
    op.create_foreign_key(
        None, "issuedbooks", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "issuedbooks", "books", ["book_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "issuedbooks", type_="foreignkey")
    op.drop_constraint(None, "issuedbooks", type_="foreignkey")
    op.create_foreign_key(
        "issuedbooks_book_id_fkey", "issuedbooks", "books", ["book_id"], ["id"]
    )
    op.create_foreign_key(
        "issuedbooks_user_id_fkey", "issuedbooks", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
