"""Add due date Column in issued Book Table

Revision ID: 58e67662b378
Revises: 7cfd0a8b543a
Create Date: 2025-05-26 12:46:31.170873

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "58e67662b378"
down_revision: Union[str, None] = "7cfd0a8b543a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("issuedbooks", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("issuedbooks", sa.Column("due_date", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("issuedbooks", "due_date")
    op.drop_column("issuedbooks", "created_at")
    # ### end Alembic commands ###
