"""change in user table

Revision ID: 7cfd0a8b543a
Revises: 158bdafd216e
Create Date: 2025-05-26 11:29:07.245059

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7cfd0a8b543a"
down_revision: Union[str, None] = "158bdafd216e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add nullable column
    op.add_column("users", sa.Column("passwords", sa.String(), nullable=True))

    # Step 2: Backfill existing rows with default (e.g., empty string)
    op.execute("UPDATE users SET passwords = '' WHERE passwords IS NULL")

    # Step 3: Alter column to NOT NULL
    op.alter_column("users", "passwords", nullable=False)

    op.drop_column("users", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("password", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("users", "passwords")
    # ### end Alembic commands ###
