"""Add returned date Column in issued Book Table

Revision ID: 975d612421a8
Revises: b8f8941dcfb7
Create Date: 2025-05-26 14:52:33.482695

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "975d612421a8"
down_revision: Union[str, None] = "b8f8941dcfb7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "issuedbooks", sa.Column("returned_date", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("issuedbooks", "returned_date")
    # ### end Alembic commands ###
