"""Add cascade logic

Revision ID: b8f8941dcfb7
Revises: 58e67662b378
Create Date: 2025-05-26 14:33:37.359869

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b8f8941dcfb7"
down_revision: Union[str, None] = "58e67662b378"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fines_issued_book_id_fkey", "fines", type_="foreignkey")
    op.create_foreign_key(
        None, "fines", "issuedbooks", ["issued_book_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "fines", type_="foreignkey")
    op.create_foreign_key(
        "fines_issued_book_id_fkey", "fines", "issuedbooks", ["issued_book_id"], ["id"]
    )
    # ### end Alembic commands ###
